[project]
org-name = "wso2"
version = "0.8.0"
authors = ["WSO2"]
keywords = ["ballerina", "gsheets", "google", "spreadsheet"]
repository = "https://github.com/wso2-ballerina/package-googlespreadsheet"
