[project]
org-name = "wso2"
version = "0.8.22"
authors = ["WSO2"]
keywords = ["gsheets", "google", "spreadsheet"]
repository = "https://github.com/wso2-ballerina/module-googlespreadsheet"
license = "Apache-2.0"
