[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "googleapis.sheets"
version = "2.2.0"
export= ["googleapis.sheets", "googleapis.sheets.listener"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Spreadsheets", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-googlespreadsheet"

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-2.2.0.jar"
groupId = "org.ballerinalang.googleapis.sheets"
artifactId = "java-wrapper"
version = "2.2.0"
