name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: SanduDS/ballerina-action/@slp8ss
              with:
                  args:
                      build -c --skip-tests
              env:
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  URL: ${{ secrets.URL }}
                  URL_ID: ${{ secrets.URL_ID }}

